### ISSUE TITLE
Add Blog Feature to Editor

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#101]
We need to add a feature that allows a person creating their own website to make a blog. There will be an "Add Blog" button, which will take them through a process. Where they want the blog to be at, comments on, or off, etc.

Then once they have created their blog we will have a blog manager, so they can post, respond to comments, etc.

**Comment by card100** [comment]
Added to https://github.com/dragon-drop-scratch/dragon-drop-scratch.github.io/issues/115
