### ISSUE TITLE
Multiple Pages in Editor

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#102]
We need to add a feature in the editor that allows users to create multiple pages. There should be a menu at the top of every site, and they can click on the menu (when in the editor) to add new pages. They could hide the menu if it was a one pager, and could add content to any page.

**Comment by card100** [comment]
Added to https://github.com/dragon-drop-scratch/dragon-drop-scratch.github.io/issues/115
