### ISSUE TITLE
Right Click

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#103]
I think that when you have an element such as a text box, you should be able to right-click on it, and it will bring up a box of options. Such as the color, font, and text size. If you wanted to make a specific change for different parts of the text you could drag over, and then right click. It would only make edits to what you have dragged over. I really think this would work great, and it could also be used for other tools.

**Comment by card100** [comment]
Added to https://github.com/dragon-drop-scratch/dragon-drop-scratch.github.io/issues/115
