### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#105]
We need to work on adding the tools below to the editor. These tools will show up on all kind of accounts.

 - [ ] Add Social Media Buttons Users Can Put In Footer
 - [ ] Add Social Media Feeds that User can put on Site
 - [ ] Slideshow (with photos)
- [ ] iFrame tool
- [ ] Be able to search for images, or upload them rather than having to find the URL and put it in. (but that    will still be an option)
 - [ ] Contact tools - add a form tool to contact, that allows you to edit the fields by right clicking
 - [ ] Title Tool - Sets the title for their site/page
 - [ ] Add a slideshow/slider tool

**Comment by card100** [comment]
I am working on a collection of different ways to show your Social Media Buttons on your website

**Comment by zspri** [comment]
@card100 Ok, check the items off of the list when you finish with them

**Comment by card100** [comment]
Added iframe tool

**Comment by zspri** [comment]
@card100 The iframe tool isn't showing up.
