### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#106]
- [x] Create Top
 - [ ] icon home
 - [ ] messages (forum and messages from us)
 - [ ] Make web manage
 - [ ] make settings:
 - [ ] -forum/support profile
 - [ ] -danger zone:
 - [ ] --delete account
 - [ ] --reset account
 - [ ] --confirm email
 - [ ] Manage Sites:
 - [ ] -List of sites
 - [ ] -Edit site
 - [ ] -Delete site
 - [ ] -Create new site
 - [ ] -Duplicate site

**Comment by coke11** [comment]
With a bit of editing this is a great issue! (remind me tomorrow)

**Comment by zspri** [comment]
Ok.

**Comment by card100** [comment]
Hmm...

**Comment by card100** [comment]
Made Top:
http://codepen.io/card100/pen/Kaepqq
Will import to Git soon

**Comment by coke11** [comment]
@card100 Can you make the dashboard go along with our color scheme better?
Would it also be possible to craft out the pages for this? And possibly make the links work?
