### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#107]
We need to have a spot in the editor where you can choose a template made by someone. We can just have a few really simple ones built in for now. You just do this in the editor, not before or after creating the site.

**Comment by coke11** [comment]
@Nanomotion Yeah, we should continue to grow on this. More important right now is the actual technology to make it happen not the templates within.

**Comment by zspri** [comment]
@coke11 That's why I added it to the backlog milestone. ;)

**Comment by card100** [comment]
https://github.com/dragon-drop-scratch/dragon-drop-scratch.github.io/issues/115
