### ISSUE TITLE
Home page needs work

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#110]
I almost think we should just redo it

**Comment by zspri** [comment]
I agree, it needs a more simple, flat look.

**Comment by coke11** [comment]
@card100 @Nanomotion I am going to make a trello notice soon about this, and it is going to say we will remake the homepage. This just convinces me to make that notice, and say we aren't using trello anymore in that notice, haha

**Comment by coke11** [comment]
Closing because in this notice we will talk about it then
