### ISSUE TITLE
Rename website and organization to "dragon-drop"

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#111]
We don't really have anything to do with Scratch anymore.

**Comment by zspri** [comment]
@card100 Why close the issue (without an explanation)?

**Comment by card100** [comment]
Oh, sorry, didn't mean to close
What's wrong with DragonDrop?

**Comment by zspri** [comment]
The organization name is "dragon-drop-scratch", since we aren't as involved with Scratch anymore, should we change it to "dragon-drop" or "DragonDrop"?

**Comment by coke11** [comment]
Yeah, I will fix this soon.

**Comment by zspri** [comment]
Okay, thanks.

**Comment by zspri** [comment]
@coke11 Could you also set the logo to our more updated one? 
![dd](https://cloud.githubusercontent.com/assets/19719195/22866215/6d88ef82-f140-11e6-8fed-459497409e5d.png)

**Comment by MeridiumDevelopment** [comment]
I think DragonDrop would be good.

Dragon-Drop just doesn't go well in my opinion.

**Comment by zspri** [comment]
True, whatever Coke decides will be fine.

**Comment by coke11** [comment]
I thought we were going to make the green dragon logo red and then use @Cythral's other logo. 

Also - I will change name now.
