### ISSUE TITLE
What needs to get done

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#115]
We are really cluttering up the issues tab with things we need to add.  Note that you can edit this post to ^
_Note:_ all tools are [here](https://github.com/dragon-drop-scratch/dragon-drop-scratch.github.io/issues/105)
These are in order of priority:
_Before_

- [ ] New page button in editor

- [ ] [Dashboard](https://github.com/dragon-drop-scratch/dragon-drop-scratch.github.io/issues/106)

- [ ] These [tools](https://github.com/dragon-drop-scratch/dragon-drop-scratch.github.io/issues/105)

- [ ] [Blogging](https://github.com/dragon-drop-scratch/dragon-drop-scratch.github.io/issues/116)

- [ ] [Animation ](https://github.com/dragon-drop-scratch/dragon-drop-scratch.github.io/issues/100)

- [ ] Editor Right Clicking

_Backlog_
- [ ] Templates

- [ ] Analytics

- [ ] Tutorials (DragonEd)

- [ ] DragonScript

This will be used just to keep track of the issues. We will still comment and stuff on the issues, but this can keep them organized.

**Comment by zspri** [comment]
The issues would've been closed when they were done, there was no point in closing them.
