### ISSUE TITLE
Blogging features

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#116]
I think we should make sure to have these features in the blogging:

- [ ] New post button

- [ ] Signature 

- [ ] Edit Post/Delete post

- [ ] Each post to have share on Twitter, Facebook, Etc. buttons

- [ ] Markdown?

- [ ] Blog on only special page

- [ ] Post date and time

- [ ] Be able to comment on post

**Comment by coke11** [comment]
I am going to close this issue for now. We are not ready to start working on blogging features, because we don't have a good backend system YET. When we are ready to start working on the blogging feature I will reopen this issue.
