### ISSUE TITLE
Can't get padding to work

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#118]
Long story, basically I can't get the padding in /dash/index.html to work.  It is currently in the index file it's self  (for now).  For some reason won't work :/.  Anyone see anything?

**Comment by zspri** [comment]
This is what I see:
![capture](https://cloud.githubusercontent.com/assets/19719195/22951759/5cd56c1c-f2d8-11e6-9e5a-67d37eedd6ce.PNG)

**Comment by card100** [comment]
Yes, top padding
