### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by csf30816** [dragon-drop-scratch/dragon-drop-scratch.github.io#121]
Do you think http://dragondrops.net needs SSL? If you do then I can work on setting up a SSL Certificate for Dragon Drop. By the way SSL is basically HTTP Security or HTTPS.

**Comment by coke11** [comment]
@csf30816 Yes - do you think you could go on Slack and guide me through putting SSL on it?

**Comment by csf30816** [comment]
Yes, what is the team name? It's been so long (:0)-]-<

**Comment by coke11** [comment]
dragondroporg

**Comment by csf30816** [comment]
Thx

**Comment by coke11** [comment]
@csf30816 Yep. Is it letting you in alright?

**Comment by csf30816** [comment]
No :(

**Comment by coke11** [comment]
Does the link not work or can you not figure out username and stuff?

**Comment by csf30816** [comment]
Username and stuff not working. What email did I signup with!!! ARGH...!! :)

**Comment by coke11** [comment]
the ttyl one

**Comment by csf30816** [comment]
OK, thanks!

**Comment by coke11** [comment]
np

**Comment by csf30816** [comment]
Um... Which one Admin or Support

**Comment by coke11** [comment]
Sorry admin

**Comment by csf30816** [comment]
We should just talk it out here :/

**Comment by coke11** [comment]
Well we will need slack anyways and it is faster and it has privacy if there are an passwords or anything so if possible we should try it this way.

**Comment by csf30816** [comment]
I got an idea

**Comment by coke11** [comment]
Alright

**Comment by csf30816** [comment]
Go to https://awatim.gq/ and click Chat Icon

**Comment by coke11** [comment]
That would work temporarily but I think it would be better just to get the long term thing sorted out. Is it not taking the username and pass or something?

**Comment by csf30816** [comment]
Yeah says email/pass is wrong

**Comment by coke11** [comment]
Are you using admin@ttyl.gq? You could try resetting the pass...

**Comment by csf30816** [comment]
I am in!

**Comment by csf30816** [comment]
I made a program that generates SSL Certificates. And one that generates UltraSecure passwords that can be millions of characters long!!

**Comment by csf30816** [comment]
so....

**Comment by coke11** [comment]
If you get on slack we can talk about this

**Comment by coke11** [comment]
We have an SSL now, we can close this up.
