### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#124]
Changing this text because Github won't let you delete, and the public doesn't need to know all that happened. - coke

**Comment by coke11** [comment]
Four things
1) I was mostly kidding
2) You could have just quit
3) Why?
4) Your welcome

**Comment by coke11** [comment]
You are not officially gone until I confirm you were not kidding. Were you or were you not

**Comment by Nanomotion** [comment]
1. That's a horrible thing to joke about.
2. I was already thinking about it.
3. 1 and 2, and we're making pretty much no progress, and many more reasons. 
4. Thanks again.

**Comment by coke11** [comment]
1. Sorry, however, you did say it and you have joked about worse things (I also said JK)
2. OK
3. That makes sense - there was progress on dragondrops.net though, and you could have helped
4. Your welcome, you were a great coder. 

ALSO - How could csf and I get less annoying? Always trying to improve.

**Comment by coke11** [comment]
If you ever want to come back let me know, we will be open.

**Comment by Nanomotion** [comment]
I was not kidding.

1. JK is like saying no offense. It means nothing.
2. --
3. You should have told me that there was work to do, I would have been happy to do it if I had time.
4. It was great being on the team while it lasted.

First of all, don't say things like twss. It's very unprofessional and I thought we were aiming to be professional. Secondly, being called things like a girl and gay is HORRIBLE. Even if you are just kidding. I'll have you know that I'm a straight male.

I might make the occasional pull request, just I won't be part of the team.

One last thanks to everyone else for a great time.

**Comment by csf30816** [comment]
Ok I get that, sorry for calling you a girl. But to be honest you did say the 'f' word.

**Comment by csf30816** [comment]
Oh and your welcome.

**Comment by Nanomotion** [comment]
I said it because I was at my boiling point, which both you and coke were pushing me to that limit. I already had a stressful day today and did not want to be bothered any more.

**Comment by csf30816** [comment]
Sorry to hear that. You did call me a ten year old. That is the equivalent of calling me a baby. But still not a big deal.

**Comment by coke11** [comment]
Ok, thank you for your time.

1 and other) I owe you an apology, I should have kept a better grip on what was going on, and drew a border between funny and mean. I personally wasn't trying to hurt your feelings and do not remember saying anything about you being gay, but that doesn't mean I didn't. And saying you were a girl I was just kidding, but am super sorry that it sounded like I was being mean. I understand completely where you are coming from.

3) Yes, I understand. But Jira was giving us problems, and the slack thing. (sorry about that too - was just trying to joke around)

Unprofessional thing) Yeah, but let's be honest every human has been unprofessional at some point and time. Plus team communication is not the same as public communication. 

Responding to your comment just a moment ago: Yes, and I take full responsibilty for my actions. I understand, and I have those days sometimes too. I wasn't trying to, I was trying to just be joking, but I understand if it did not come out that way. Please let me know if you need anything else, and I am sorry for anything that hurt your fellings, I was just trying to joke, every time it seemed to be that way, but I am sorry if it did not come out right.

**Comment by GreenBayRules** [comment]
#WorstDayInDDHistory

**Comment by Nanomotion** [comment]
@coke11 I owe you an apology too. I was overreacting at first. 

--
Also there have been lots of times I've been unprofessional.

**Comment by coke11** [comment]
@Nanomotion It's alright - btw are you nanonew on the chat?

**Comment by coke11** [comment]
@Nanomotion Is it your or not?

**Comment by coke11** [comment]
@csf30816 Sorry - we were just trying to bring the mood up, but it totally backfired. Did we just lose another amazing member?

**Comment by Janbuller** [comment]
I actually saw it 😄

**Comment by Janbuller** [comment]
1: Nanomotion thought that coke11 had fired him when coke11 said JK in the end.
Nanomotion then said that it was like saying No Offense and that it meant nothing
2: Nanomotion didn't like being called "Gay" and "Girl" but coke11 didn't remember saying "Gay" but did remember calling him a "Girl" saying it was just for fun
3: Nanomotion thought that everything was unprofessional and thought that it was supposed to be professional coke11 replied saying that there is a difference between inside talk and customer communication.

**Comment by zspri** [comment]
@coke11 You can restrict the conversation to collaborators only

**Comment by coke11** [comment]
@Janbuller - That's fine  - I just decided that I should delete it so no one else did.

**Comment by coke11** [comment]
@Nanomotion How? Also, is one card still part of DragonDrop now?

**Comment by zspri** [comment]
Click on 'Lock conversation' on the right. It can be -- I still want it to be, since I won't be able to complete it without someone who does backend. If you need I can invite the DD team to the OneCard org.

**Comment by coke11** [comment]
Yeah, I understand. You and CSF could just work on it?
