### ISSUE TITLE
Your Link Dns Needs To be Renewed.

### ISSUE THREAD

**Issue by radioblahaj** [dragon-drop-scratch/dragon-drop-scratch.github.io#129]
^^^^^^

**Comment by zspri** [comment]
What part of "This project has been abandoned" do you not understand?

**Comment by Sheshank-s** [comment]
@coke11 can you add "This has been abandoned" to the description plz?

**Comment by RedMAngo22** [comment]
I'm Forking all of dragondrop's stuff to make something with dragondrop code. I want help!

**Comment by zspri** [comment]
If one of the org members can close this...
