### ISSUE TITLE
Where's the GitHub preview site?

### ISSUE THREAD

**Issue by MeridiumDevelopment** [dragon-drop-scratch/dragon-drop-scratch.github.io#18]
Somewhere I managed to find like a github.io site of DragonDrop which had index.html. Do any of you people know what the URL is?

**Comment by coke11** [comment]
@golden-scratch This was the test site. I am working on getting the normal site up on gh-pages.

**Comment by coke11** [comment]
If you want the test site url I think it is dragon-drop-scratch.github.io/backup

**Comment by coke11** [comment]
@golden-scratch I have got the normal site up on GHpages for testing. It can be accessed here
http://dragon-drop-scratch.github.io/dragon-drop-www

**Comment by MeridiumDevelopment** [comment]
Thank you.

**Comment by coke11** [comment]
No problem 

_adri326: Huh I can edit comments from other people?_

**Comment by radioblahaj** [comment]
Hi

**Comment by adri326** [comment]
Hey! I'm surprised to find you here :)

**Comment by radioblahaj** [comment]
Do you know me? From scratch you follow me on @scratchworldcup on scratch?

**Comment by adri326** [comment]
I saw you one time on scratch... were you part of the pokemon land and sea project or the newawe project? Or... I don't know, but I saw you one time on scratch, I have the same pseudo on it

**Comment by radioblahaj** [comment]
The never did a Pokémon project 

Warm regards,

Arav Narula

On Sun, Oct 2, 2016 at 3:09 AM -0400, "adri326" notifications@github.com wrote:

I saw you one time on scratch... were you part of the pokemon land and sea project or the newawe project? Or... I don't know, but I saw you one time on scratch, I have the same pseudo on it
