### ISSUE TITLE
Bug on home (index)

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#22]
Sign Up button moves when pressed on

**Comment by coke11** [comment]
This is a known bug, and I am currently fix it. 

Update: Can't seem to figure it out. @csf30816 - Could you take a look?

**Comment by csf30816** [comment]
OK, I noticed this too

**Comment by coke11** [comment]
@csf30816 - Any idea as to why this might be happening?

**Comment by csf30816** [comment]
Yes, and I just fixed it
