### ISSUE TITLE
Contact Form Not load CSS

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#24]
The contact form (at least for me) did not load the CSS.
https://dragon-drop-scratch.github.io/dragon-drop-www/Contact.html

**Comment by coke11** [comment]
Not loading for me either. Let me take a look...

**Comment by coke11** [comment]
It doesn't look like there is a CSS file for the Contact page. Maybe it got deleted. Strange!

**Comment by csf30816** [comment]
I got this

**Comment by card100** [comment]
Fixed
