### ISSUE TITLE
No CSS on 404 Page

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/dragon-drop-scratch.github.io#25]
I recently received a 404 and it looked like this:
![no css](https://cloud.githubusercontent.com/assets/18141280/17501099/1d437e30-5da1-11e6-9e62-ee7011cb56d7.png)
As you can tell, the CSS is NOT there. I tried going to /404 and the CSS was there. What is going on?

**Comment by ghost** [comment]
Ahhh.  I see.  They were using relative (like `/hi`) css urls instead of direct (like `http://site.com/hi`).

**Comment by csf30816** [comment]
It looks fine to me: 
![capture](https://cloud.githubusercontent.com/assets/18520232/17523346/dbf97f2c-5e1f-11e6-848d-7cf9f11fd45c.JPG)

**Comment by card100** [comment]
Fine for me too

**Comment by coke11** [comment]
How were you getting there? Did you go /404? This is when I get it from really typing the wrong address.

**Comment by coke11** [comment]
Cannot repro because of #57. See comment there - for time being this is closed.
