### ISSUE TITLE
Contact Us page requires Scratch username

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#27]
Contact Us page requires a Scratch username.  Can only Scratcher's contact us?

**Comment by coke11** [comment]
Originally it asked for email, but because of a request from the Scratch Team it now ask for the Scratchers username. We are trying to figure out a way for non scratchers to be able to use email :)

**Comment by csf30816** [comment]
How about username, since both use a username

**Comment by coke11** [comment]
What if someone doesn't have a username on Dragon Drop?

**Comment by csf30816** [comment]
Then why would they be contacting?
