### ISSUE TITLE
Contact Page form on top of menu bar

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/dragon-drop-scratch.github.io#28]

**Comment by csf30816** [comment]
OH, I have absolutly no idea how to fix this at all ask the one who made the form

**Comment by coke11** [comment]
@packersrulegopack and I made it. I am working on fixing it

**Comment by csf30816** [comment]
OK

**Comment by Sheshank-s** [comment]
Done

**Comment by coke11** [comment]
@GreenBayRules Thanks - 2 points
