### ISSUE TITLE
Log In page Nav Bar Down

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#38]
![log in bug](https://cloud.githubusercontent.com/assets/17168923/17592753/141584a2-5fa9-11e6-800d-03be7655d44b.png)

**Comment by coke11** [comment]
@csf30816 @CosmicWebServices @card100 bump

**Comment by zspri** [comment]
I'm pretty sure someone fixed this.

**Comment by Sheshank-s** [comment]
@NaturalmotionStudios Yep i did!
