### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/dragon-drop-scratch.github.io#42]
The Contact Us page should ask if you are a Scratch user or not, and if so show the 1st form, and if not show the second form. Anyone want to do this?

(I am working on getting us hooked up with fresh desk)

**Comment by Sheshank-s** [comment]
Fixed!

**Comment by coke11** [comment]
Not showing on my end....

**Comment by Sheshank-s** [comment]
Really! It seems to work for me...

**Comment by Sheshank-s** [comment]
Oh now i get what you mean!

**Comment by Sheshank-s** [comment]
I only see one form, I will add another one...

**Comment by Sheshank-s** [comment]
Ok it works now, but it just needs more css, and I need to make the Scratcher Contact
