### ISSUE TITLE
Error on terminal

### ISSUE THREAD

**Issue by CosmicWebServices** [dragon-drop-scratch/dragon-drop-scratch.github.io#45]
c:/Users/shesh_000/Downloads/79A0zk.png 
Failed to load resource: unsupported URL
On credits.html

**Comment by MeridiumDevelopment** [comment]
All I know is that the unsupported URL comes because it's a file destination...

I'll assign some developers on the Trello, as I have not yet seen that error. Also the .png file is the signature, not the top image on the Credits.HTML page.

**Comment by CosmicWebServices** [comment]
OK thanks!

**Comment by coke11** [comment]
@csf30816 - Do you have time to look into this?

**Comment by Sheshank-s** [comment]
Oops! Sorry that was me, i will fix it!

**Comment by csf30816** [comment]
It looks like it is fixed: 
![capture](https://cloud.githubusercontent.com/assets/18520232/18023547/e867abe6-6bbf-11e6-980b-ca8f89c85187.PNG)
So I am closing this :)

If it is not fixed please tell me what is wrong, and I will re-open this, thank you - Csf30816
