### ISSUE TITLE
Animation in footer 

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/dragon-drop-scratch.github.io#47]
Look at the footer as you scroll down in chrome

Not able to repro in Safari
Unknown for firefox

**Comment by csf30816** [comment]
I just see the normal footer :) I do not see the GIF in it. 
![capture](https://cloud.githubusercontent.com/assets/18520232/18023455/ded183e6-6bbe-11e6-8d09-df050979b21b.GIF)
![capture](https://cloud.githubusercontent.com/assets/18520232/18023478/2beb6b42-6bbf-11e6-94c8-d35086204a2a.GIF)

**Comment by coke11** [comment]
@csf30816 Interesting... Staging?

**Comment by zspri** [comment]
I didn't know there was supposed to be a GIF in the footer, and I think it looks better this way.

**Comment by CosmicWebServices** [comment]
I think we should remove it makes no sense why we need an animate footer

**Comment by Sheshank-s** [comment]
We need a footer.. When I made. The footer i didn't add any animation., it's a problem with the existing css

**Comment by CosmicWebServices** [comment]
Oh well I will check it out

**Comment by coke11** [comment]
I have found another piece of info. This only happens on the homepage. Not the other pages with the footer. Could it possibly have to do with the homepage?

**Comment by Sheshank-s** [comment]
I know the problem. Someone put the animation in the css of the homepage

**Comment by coke11** [comment]
@GreenBayRules AH, ok. Do you think you could put together a quick fix for this

**Comment by Sheshank-s** [comment]
Hmm I am not sure. I do know that card100 made the animation for a different element in the homepage, and then deleted that element, but not the css (Im guessing?)

**Comment by csf30816** [comment]
Fixed

**Comment by coke11** [comment]
@csf30816 @GreenBayRules @card100 Thank you for all your hard work on this!
