### ISSUE TITLE
Credits Page

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/dragon-drop-scratch.github.io#48]
Can we add the following text to the credits page? 

> # The following users have done everything they can to make sure the DragonDrop wiki has the best content out there, and is up to date:
> 
> golden-scratch | Austinato | card100

(linking to their profiles of corse)

I also added a little more at the bottom of the credits page, if anyone is interested in making it look better (I could easily edit it myself, but am trying to catch up on what all happened when I was gone.)

thanks

**Comment by CosmicWebServices** [comment]
I will do this today

**Comment by coke11** [comment]
Awesome, you are the best

**Comment by CosmicWebServices** [comment]
Aww
