### ISSUE TITLE
Copied code?

### ISSUE THREAD

**Issue by matthewr6** [dragon-drop-scratch/dragon-drop-scratch.github.io#49]
[Your footer.jsx](https://github.com/dragon-drop-scratch/dragon-drop-www/blob/gh-pages/footer.jsx) and [scratch-www's footer](https://github.com/LLK/scratch-www/blob/develop/src/components/footer/www/footer.jsx) seem extremely similar.  If you do plan on using it, you might want to take a look at [scratch-www's licence](https://github.com/LLK/scratch-www/blob/develop/LICENSE) ;)

**Comment by coke11** [comment]
I agree. This was just a simple template we were using, that would never get in the final product. Deleting the file now
