### ISSUE TITLE
Code ownership

### ISSUE THREAD

**Issue by matthewr6** [dragon-drop-scratch/dragon-drop-scratch.github.io#50]
According to [this](http://opensource.stackexchange.com/questions/2907/does-the-owner-of-the-github-repository-own-the-copyright-to-the-code), you can't just claim copyright ownership of any code that's contributed, unless

> you have signed a copyright assignment agreement

**Comment by coke11** [comment]
OK? This code is all original

**Comment by matthewr6** [comment]
I'm referencing this:

> Warning! Any code contributed is owened _(sic)_ by Dragon Drop.

**Comment by coke11** [comment]
Ah, ok. Thanks for letting me know

**Comment by coke11** [comment]
c/c @golden-scratch Please remove this from the redeem file. Thank you

**Comment by matthewr6** [comment]
Redeem the readme!  :tada:

**Comment by MeridiumDevelopment** [comment]
Removed statement. ;)
Closed.
