### ISSUE TITLE
Footer is broken

### ISSUE THREAD

**Issue by CosmicWebServices** [dragon-drop-scratch/dragon-drop-scratch.github.io#51]

**Comment by coke11** [comment]
How is the footer broken?

**Comment by CosmicWebServices** [comment]
keep scrolling down

**Comment by coke11** [comment]
Is it the animation?

**Comment by CosmicWebServices** [comment]
no clue

**Comment by CosmicWebServices** [comment]
I will take a screenshot

**Comment by CosmicWebServices** [comment]
![screen shot 2016-08-23 at 12 00 19 pm](https://cloud.githubusercontent.com/assets/10731781/17899409/47c4183e-6929-11e6-9bb7-04009d79bb79.png)

**Comment by coke11** [comment]
This is a known bug. No one knows how to fix it

**Comment by CosmicWebServices** [comment]
OK
