### ISSUE TITLE
DB password in code

### ISSUE THREAD

**Issue by towerofnix** [dragon-drop-scratch/dragon-drop-scratch.github.io#53]
If this password is used _anywhere_ else, change it _immediately_. You can't get rid of that password from this repository's history.

See scratcher.php.

**Comment by zspri** [comment]
Thank you for letting us know, I've temporarily censored it. :)

**Comment by CosmicWebServices** [comment]
problem you can go to the commit history and still see it

**Comment by coke11** [comment]
This pass is not used anywhere else, it is a test database just for DragonDrop with the username as the password of one of our members

**Comment by CosmicWebServices** [comment]
ok

**Comment by csf30816** [comment]
Yes, I noticed that when I made the code, I was hoping that we could save it somewhere and delete it from Github or something else, if you want I can change the password for the DB

**Comment by coke11** [comment]
@csf30816 Just change the pass, thanks

**Comment by csf30816** [comment]
OK, EDIT: Password Changed :)
