### ISSUE TITLE
Bugs with Organizing (Mostly done)

### ISSUE THREAD

**Issue by Sheshank-s** [dragon-drop-scratch/dragon-drop-scratch.github.io#54]
I made everything folders, and many bugs came up. I fixed almost all of them except for one, which I really don't want to do. Basically someone has to go through and replace all the "./EXAMPLE_PAGE.html" with "dragon-drop-scratch.github.io/dragon-drop-www/FOLDER_NAME/EXAMPLE_PAGE.html" I really don't want to do it because I just went through and fixed a TON of bugs that came with organizing the files. Someone should finish this by September 4th, because this is a big issue.

**Comment by coke11** [comment]
Thanks for the report :). Please remember to only assign to 3 people at the most for now on though, thanks :)

**Comment by coke11** [comment]
C/c could you look into this @csf30816 Prio high

`Comment From @Csf30816: - What does Prio high mean?`

**Comment by coke11** [comment]
We should also make an info folder

**Comment by csf30816** [comment]
You do not have to replace it with `dragon-drop-scratch.github.io/dragon-drop-www/FOLDER_NAME/EXAMPLE_PAGE.html` you can replace it with `../EXAMPLE_PAGE.html` you put '.'s where ever a folder name is :)

**Comment by Sheshank-s** [comment]
@coke11 @csf30816 @card100 So whos doing this?

**Comment by zspri** [comment]
Fixed the links on Credits.html

**Comment by Sheshank-s** [comment]
I already fixed all of them. Including the credits link😜

**Comment by coke11** [comment]
@GreenBayRules Have you fixed this or not? It sounds like you have, but this is still open :/

**Comment by Sheshank-s** [comment]
Yeah I did😀

**Comment by coke11** [comment]
@GreenBayRules A few pages still aren't working...

**Comment by Sheshank-s** [comment]
Ok csf finished the rest!

**Comment by coke11** [comment]
@GreenBayRules Thank you!
