### ISSUE TITLE
Fix the 404 page

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#57]

**Comment by csf30816** [comment]
Fixed

**Comment by zspri** [comment]
Thanks

**Comment by zspri** [comment]
This isn't fixed...

**Comment by coke11** [comment]
#25

**Comment by coke11** [comment]
@csf30816 How did you fix?

At first I thought it was just the CSS that was broken

**Comment by zspri** [comment]
No... It's the Github 404, not ours. It's probably because it's in /ErrorPages/.

**Comment by coke11** [comment]
ah. I can put together a quick fix for this.

**Comment by coke11** [comment]
Although I am wondering if this would still happen on my servers... Let's not do anything with this issue, and remind me later to try to fix it & test on our servers.

**Comment by csf30816** [comment]
Fixed

**Comment by csf30816** [comment]
Um, when we put it on your servers instead of having 404.md, 503.md, and 403.md we will have to have .htaccess with the following code:

`ErrorDocument 403 /403.html`
`ErrorDocument 404 /404.html`
`ErrorDocument 503 /503.html`
`ErrorDocument 500 /500.html`
