### ISSUE TITLE
Credits page

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/dragon-drop-scratch.github.io#58]
I added a new section on the credits page that reads 

> ```
>  These people help with DragonDrop in a loosely organized format, contributing to many parts of the project.
> ```

Can we add these users and their profile pics? Thanks

m99900
pioutch
Pufflegamerz
Austinato
makethebrainhappy

Also - Can we get rid of Austinato from the last section? Then add another section with websites that helped us. 

We also need all profile picks in the last section. Thanks again!

**Comment by Sheshank-s** [comment]
Sure I'll do this once I get home.. I might not be as active now that school started.

**Comment by coke11** [comment]
@GreenBayRules Sounds great - Thanks

BTW that is no problem. Just make sure you do your assigned jobs, and get 10 points a week. (this job is worth 3 points. If possible submit this as a PR rather then just making the edit. Thanks

**Comment by Sheshank-s** [comment]
Ok I already have 42 points

**Comment by coke11** [comment]
@GreenBayRules The ones for orgranizing don't count yet because it is not done. but ya

**Comment by Sheshank-s** [comment]
Yeah they are.. The bugs are all gone

**Comment by coke11** [comment]
hm, ok. I just saw one like 2 secs ago...

**Comment by coke11** [comment]
@NaturalmotionStudios do you think you would be able to take care of this? thanks

**Comment by zspri** [comment]
@coke11 Ok

Sorry I wasn't here to help that much for the past 3 days.

**Comment by coke11** [comment]
@NaturalmotionStudios @csf30816 Who wants to do this?

**Comment by zspri** [comment]
@coke11 Me!

**Comment by zspri** [comment]
Finished (I think)

**Comment by coke11** [comment]
THANK YOU

**Comment by Sheshank-s** [comment]
This was finished a while ago

Sent from my iPhone

On Sep 16, 2016, at 4:55 PM, coke11 <notifications@github.com<mailto:notifications@github.com>> wrote:

THANK YOU

##

**Comment by coke11** [comment]
It was? Please close these issues when finishing them, thanks

**Comment by Sheshank-s** [comment]
Sorry I forgot!! Will remember next time

Sent from my iPhone

On Sep 17, 2016, at 4:54 AM, coke11 <notifications@github.com<mailto:notifications@github.com>> wrote:

It was? Please close these issues when finishing them, thanks

##

**Comment by zspri** [comment]
@coke11 np

**Comment by coke11** [comment]
@GreenBayRules It's fine :)

**Comment by Sheshank-s** [comment]
:D

Sent from my iPhone

On Sep 17, 2016, at 11:47 AM, coke11 <notifications@github.com<mailto:notifications@github.com>> wrote:

@GreenBayRuleshttps://github.com/GreenBayRules It's fine :)

##

**Comment by coke11** [comment]
@golden-scratch Any chance you could add a website credits section?

**Comment by coke11** [comment]
Or should I take it?

**Comment by zspri** [comment]
xD

(Edit: I did this at school :P)

**Comment by Sheshank-s** [comment]
Um I dont understand, this was fixed!

**Comment by radioblahaj** [comment]
#79

**Comment by zspri** [comment]
![capture](https://cloud.githubusercontent.com/assets/19719195/19268035/07f7d1a0-8f80-11e6-9f7d-8dc2f85b802f.PNG)

The credits look kind of weird now.

**Comment by Sheshank-s** [comment]
@NaturalmotionStudios Yes, I am fixing them.... I made it look like that, and I will fix it :D

**Comment by Sheshank-s** [comment]
@NaturalmotionStudios I think it is done.

**Comment by zspri** [comment]
@GreenBayRules Thanks! It looks a lot better now.

**Comment by Sheshank-s** [comment]
Thanks

Sent from my iPhone

On Oct 11, 2016, at 2:55 PM, Nanomotion <notifications@github.com<mailto:notifications@github.com>> wrote:

@GreenBayRuleshttps://github.com/GreenBayRules Thanks! It looks a lot better now.

##

**Comment by radioblahaj** [comment]
where's who helped the dragondrop team and are not in part of dragondrop
and the page looks more werid, can we go back to what we had before
@greenbayrules? Did you get coke approval on chaging the credits page?
@coke11

**Comment by radioblahaj** [comment]
@CARD100 forget to add you abbove on the comment can you check for bugs
please !

**Comment by radioblahaj** [comment]
here's the screenshot shows words do not come good[image:
Screenshot_20160927-212946.png]

**Comment by radioblahaj** [comment]
sending , give me some time wrong one

**Comment by radioblahaj** [comment]
can we have it back like the screenshot i sent/?

**Comment by radioblahaj** [comment]
![7105534_60x60](https://cloud.githubusercontent.com/assets/21000033/19330816/a5dbafc0-90ae-11e6-8e26-af0c382ce1ba.png)
![Uploading 7680480_60x60.png…]()
![8901920_60x60](https://cloud.githubusercontent.com/assets/21000033/19330817/a5dc315c-90ae-11e6-9d4e-94aba75c8d58.png)
![11689214_60x60](https://cloud.githubusercontent.com/assets/21000033/19330819/a5dd14aa-90ae-11e6-9692-dd74e4b7be40.png)
![16844036_60x60](https://cloud.githubusercontent.com/assets/21000033/19330820/a5dd5140-90ae-11e6-802f-9c2558c42d7a.png)
![Uploading costume1.png…]()

**Comment by radioblahaj** [comment]
Sorry , wrong file how do you take a screenshot on windows?

**Comment by radioblahaj** [comment]
the screenshot is in the html file thanks you zebrauislrearning

**Comment by Sheshank-s** [comment]
[Note added by golden-scratch: Please do not be disrespectful and more rather ask for them to explain more carefully. Thanks.]

**Comment by Sheshank-s** [comment]
I did get cokes approval and he said it was good. Everyone else likes it the new way. The old way didn't look professional! @zebraislearning

**Comment by radioblahaj** [comment]
I,am saying that I liked the old look for the credits page not the 2 new
ones!
People who helped won't have credit and it is not fair!!

**Comment by Sheshank-s** [comment]
@zebraislearning [removed by coke - please remember to be respectful] and also, everyone else likes the new look better. We need to be professional. [removed - please read above]

**Comment by radioblahaj** [comment]
Who typo

**Comment by radioblahaj** [comment]
@greenbayrules, people who helped you need credit if you are not going to
put back to the old you maybe you do have any inavite for the people Zhou
helped and were not in the team!

@coke11 might be the leader but you can not leave someone or something's
out I can have a chat with him!

**Comment by Sheshank-s** [comment]
@zebraislearning FYI:: To take a screenshot in Windows: Go to Cortana (Search) and type "Snipping Tool".

**Comment by Sheshank-s** [comment]
What on earth does  "Who Typo" mean?

**Comment by radioblahaj** [comment]
But you used to have the who helped the dragondrop team but not are part of
the DD team! I made a typo so I meant typo in who (Wrong spelling) I am
helping the team and if you hate it just say @stop #Stop

**Comment by Sheshank-s** [comment]
@zebraislearning What does "Zhou" mean? What does "inavite" mean? Actually, I don't need to have someone, who has made no contributions to the credits. Give me one example of you helping?

**Comment by radioblahaj** [comment]
FYI: I have helped the team in many things!

**Comment by radioblahaj** [comment]
Um making issues and making sure the website is perfect and trying my best
to help every DD member you can ask @coke11 about it ! I made a typo on
Zhou I meant who and inavite means not doing right things I spelled the
word wrong

**Comment by Sheshank-s** [comment]
First of all: No, I was the first person hired on to DD. 
Second Thing: I said give me examples
[removed - please remember to be respectful]

**Comment by Sheshank-s** [comment]
[removed - please remember to be respectful]

**Comment by radioblahaj** [comment]
I did helpppp!

**Comment by Sheshank-s** [comment]
Sorry to break it to you, but you really didn't :P If you did, you would be on the team. You would be in the trello we have. In the Gitter we have. 

[Remember to be respectful!]

**Comment by Sheshank-s** [comment]
There is a way you could help though....

**Comment by Sheshank-s** [comment]
Comment help if you want to...

**Comment by radioblahaj** [comment]
Here's an great example: The DD team needs someone who's good at finding
bugs I took the thing and did it! How would I know there were like 55
closed!!

#sorrybutileanididhelp

**Comment by radioblahaj** [comment]
Like what?

**Comment by Sheshank-s** [comment]
Do you know HTML?

**Comment by radioblahaj** [comment]
What's that

**Comment by Sheshank-s** [comment]
or CSS, or JavaScript

**Comment by Sheshank-s** [comment]
[Please do not ask for personal info - thank you]

**Comment by radioblahaj** [comment]
No

**Comment by Sheshank-s** [comment]
Ok

**Comment by Sheshank-s** [comment]
Are you good at art?

**Comment by radioblahaj** [comment]
I wanted to be a designer for DD but I entered too late
Between 8 and 12 ! Good at art!

**Comment by radioblahaj** [comment]
Y

**Comment by Sheshank-s** [comment]
Hmmm

**Comment by Sheshank-s** [comment]
Could you send "sheshank@outlook.com" some pics of your art?

**Comment by Sheshank-s** [comment]
Could I take a guess that your age is 10?

**Comment by radioblahaj** [comment]
Warm regards,

Arav NarulaI will try

On Wed, Oct 12, 2016 at 7:38 PM -0400, "Sheshank Shankar" notifications@github.com wrote:

Could you send "sheshank@outlook.com" some pics of your art?

**Comment by radioblahaj** [comment]
Near

Warm regards,

Arav Narula

On Wed, Oct 12, 2016 at 7:39 PM -0400, "narula arav (rv.n)" aravnarula18@gmail.com wrote:

Warm regards,

Arav NarulaI will try

On Wed, Oct 12, 2016 at 7:38 PM -0400, "Sheshank Shankar" notifications@github.com wrote:

Could you send "sheshank@outlook.com" some pics of your art?

**Comment by Sheshank-s** [comment]
:D

**Comment by Sheshank-s** [comment]
I haven't recieved anything yet..

**Comment by radioblahaj** [comment]
Wait

**Comment by Sheshank-s** [comment]
Ok. Do you know how to attach a picture through email.

**Comment by radioblahaj** [comment]
Y

**Comment by Sheshank-s** [comment]
So you can send me a email with an example of your art. You can attach it here if you want..

**Comment by Sheshank-s** [comment]
?

**Comment by GreenBayRules** [comment]
So your gone? @zebraislearning Ok then, bye!

**Comment by MeridiumDevelopment** [comment]
@GreenBayRules Please remember to be respectful and mindful. I have read your conversation same as Coke has. Such responses are unacceptable for your position you have been given. Act like you deserve the position and you are grateful for it.

Also: A person who find's bugs doesn't always need to know HTML. Though it would help. Zebra's job is to find typos, and any visual bugs, by testing all new features as soon as they're done.

**Comment by MeridiumDevelopment** [comment]
@zebraislearning You have been helping and the team have been appreciating that. Thank you. The disrespect is being looked into further.

**Comment by radioblahaj** [comment]
Thanks @golden-scratch

**Comment by Sheshank-s** [comment]
@golden-scratch If thats what you think, then thats what you think. Maybe think of it from my angle :P.

Packers,

I am very sorry about all of this. I understand that it can be hard when someone doesn't quite agree with you. However - These privileges that have been giving to you as a coder for DragonDrop are big ones, and you must use them responsibly. We have to make sure that DragonDrop looks good, and it doesn't look like we are bullying people. That is not acceptable by all means. Thank you for your time.

Coke11
CEO 
DragonDrop

**Comment by radioblahaj** [comment]
You are acting like a cyber bully stop now please!

**Comment by Sheshank-s** [comment]
@zebraislearning You got your wish. I quit Dragon Drop.

**Comment by Sheshank-s** [comment]
@golden-scratch ^

**Comment by Sheshank-s** [comment]
@golden-scratch I was asking if he  could be a designer not a coder. I thought maybe since he said he was good at art, and since we don't have much designers on your team.

**Comment by Sheshank-s** [comment]
Its weird how github lets you edit others comments D:. 

[The following is a note from coke: You have to be in the org - as you have quit you can no longer edit other people's comments - I hope you decide to come back. In the case that you do I will add back :)]

**Comment by MeridiumDevelopment** [comment]
@GreenBayRules It's not Zebra's or my wish for you to quit. @zebraislearning just wants you to treat them better, as you have been being disrespectful. Zebra was also never a coder, and it's not my team... It's more like 'our' team.

I really wouldn't like you to quit after all the great work you've done. Please. 

My life has been hard recently. I don't want to lose more things.

**Comment by coke11** [comment]
@zebraislearning 

Arav,

I am very sorry to hear about this and agree with Seb 100%. Bullying should not be acceptable at DragonDrop from any degree. No matter who it is from, or where; even if it is borderline it does NOT go under my watch. Seb and I are currently working on sorting this out, and removing anything that was not kind. I hope Sheshan does realize that his actions were not OK and decides to apologize. 

In the meanwhile, I would not like this to discourage you from helping with DragonDrop further. You are a great person, and your many things you have done for DragonDrop are very much appreciated. 
I am going to close this conversation just to prevent any more flame wars. If you need to contact me, please do so either on Scratch or by emailing me at coke11scratch@gmail.com. Thank you so much for your time!

Coke11
CEO
DragonDrop

**Comment by Sheshank-s** [comment]
So coke ur firing me? ;-; Im literally crying at this moment so much time wasted just to be fired 😭

**Comment by coke11** [comment]
@GreenBayRules No - I am not firing you. You just said you would like to quit. I hope you do decide to come back.

**Comment by coke11** [comment]
@GreenBayRules If you would like to come back, please do. I will add you back to Github, and Trello, and what not.

**Comment by coke11** [comment]
@GreenBayRules Are you still on?

**Comment by Sheshank-s** [comment]
Packers,

I am very sorry about all of this. I understand that it can be hard when someone doesn't quite agree with you. However - These privileges that have been giving to you as a coder for DragonDrop are big ones, and you must use them responsibly. We have to make sure that DragonDrop looks good, and it doesn't look like we are bullying people. That is not acceptable by all means. Thank you for your time.

Coke11
CEO 
DragonDrop

Isn't this not a firing letter? Also, I prefer Packers rather than "Sheshank" I get bullied a lot at school because of my name, so I don't like to be addressed with that name :(

Also, I do want to stay with DD, I was mad so I said mean things and Im sorry.

**Comment by Sheshank-s** [comment]
Yes

**Comment by Sheshank-s** [comment]
So what am I losing from all of this? @coke11

**Comment by coke11** [comment]
@GreenBayRules Oh, I am so very sorry for calling you by your first name! I can just imagine how hard it would be for that to happen.

No - It was just a simple reminder. I will add you back to everything now :D

**Comment by coke11** [comment]
@GreenBayRules Nothing. Again, I am so sorry!

**Comment by coke11** [comment]
@GreenBayRules I just need to make sure that DragonDrop is a friendly place for everyone :D

**Comment by Sheshank-s** [comment]
About the name? Thats fine :) Its  just I don't like it because almost EVERYONE butchers it...

**Comment by coke11** [comment]
@GreenBayRules I understand. I think you have a great name though :).

**Comment by Sheshank-s** [comment]
lol.

**Comment by coke11** [comment]
@GreenBayRules Ok! Invited you back to GitHub. You will just need to accept the invite. Adding you back to Trello now  :D

**Comment by Sheshank-s** [comment]
I did.

**Comment by Sheshank-s** [comment]
Is all my progress gone now? @coke11

**Comment by coke11** [comment]
@GreenBayRules Awesome! I love seeing that label by your name again :)

**Comment by coke11** [comment]
@GreenBayRules Nope! When recovering your account, I made sure I got it back :D

**Comment by Sheshank-s** [comment]
Oh ok...

**Comment by coke11** [comment]
![commit](https://cloud.githubusercontent.com/assets/18141280/19368167/61ed6c5c-9164-11e6-82ed-095a4452fc9f.png)

**Comment by Sheshank-s** [comment]
I need to go, bye.

**Comment by coke11** [comment]
@GreenBayRules Bye - Have a great day :D

**Comment by Sheshank-s** [comment]
Whats that?

**Comment by coke11** [comment]
@GreenBayRules Oh - Just a commit you made, just making sure you didn't lose progress :)

**Comment by Sheshank-s** [comment]
Oh ok.

**Comment by Sheshank-s** [comment]
@coke11 Im back, ,anything I should do?

**Comment by coke11** [comment]
@GreenBayRules Just anything that is on Trello :)

**Comment by Sheshank-s** [comment]
Ok.

**Comment by radioblahaj** [comment]
Thanks coke11!! I have been waiting for a response from one of the people
who own dragondrop! Thanks , ZEBRA p.s. I am a boy!

**Comment by radioblahaj** [comment]
Hi @coke11 How is dragondrop going so far?

**Comment by coke11** [comment]
@zebraislearning DragonDrop is doing great! We are considering your QA request currently :)

**Comment by radioblahaj** [comment]
So would I be part of team!

**Comment by Sheshank-s** [comment]
Yeah. Once coke accepts your request.

**Comment by radioblahaj** [comment]
THX
Warm regards,

Arav Narula

```
    _____________________________
```
