### ISSUE TITLE
Text on homepage not showing up

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/dragon-drop-scratch.github.io#60]
The following text:

> No programming or development knowledge needed. Just start making your free website today, and have it done in minutes!

is not showing up on the homepage. The first part shows up and then it stops going

**Comment by zspri** [comment]
It's probably just something wrong with the CSS.

**Comment by zspri** [comment]
Not sure what's wrong. Ask @GreenBayRules, he made it.

**Comment by Sheshank-s** [comment]
Ok fixed!
