### ISSUE TITLE
CSS broken on certain pages

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#61]
scratcherformSignUp.html
normalusersignup.html
login.html
userpage-example.html

and a couple more.

**Comment by csf30816** [comment]
I got this

**Comment by csf30816** [comment]
That should do it :)

**Comment by coke11** [comment]
@csf30816 thanks

**Comment by zspri** [comment]
@csf30816 Thanks
