### ISSUE TITLE
Issues with "Sign in with Google" button

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#62]
(The following was provided by coke11, because for some reason I can edit other people's responses from my account)
(Thats weird I can too!)
The nav bar bug was fixed. Now we need to focus on the button not working at all. I get a google error

**Comment by csf30816** [comment]
I got this

**Comment by csf30816** [comment]
There is nothing we can do about this, it is the Google CSS that makes it like this. there is a `position: relative;` in there CSS and we can not make it a `position: initial;` or `­`

**Comment by zspri** [comment]
Ok, thanks

**Comment by Sheshank-s** [comment]
Let me try to fix this...

**Comment by Sheshank-s** [comment]
Done!

**Comment by Sheshank-s** [comment]
What! I fixed it! Why is this re-opened.

**Comment by coke11** [comment]
This never ended up getting fixed. I have assigned @NaturalmotionStudios as they were the one who was hooking it up in the first place. Also - We need to do it with a DragonDrop google account, not @NaturalmotionStudios's. That would make it look better, and then other people could make edits :)

**Comment by coke11** [comment]
@GreenBayRules Hm. I still get the error

**Comment by coke11** [comment]
@GreenBayRules oh. I was mixed up when it comes to this issue. I am going to make a couple of changes to it

**Comment by Sheshank-s** [comment]
Yes it did. The issue was the Sign up bar was going in front of the nav bar. See: 
![i fixed it](https://cloud.githubusercontent.com/assets/11379161/18811069/33d7a5c0-825b-11e6-8d7b-3e14668ff06a.GIF)

**Comment by Sheshank-s** [comment]
Oh ok. I remember gixing this :) Whats the new problem?

**Comment by coke11** [comment]
@GreenBayRules Yes - I miss understood you. I forgot that is what the issue was for. Now I am going to report the new problem

**Comment by coke11** [comment]
@GreenBayRules - Updated the main description. Do you think you would be able to fix it?

**Comment by Sheshank-s** [comment]
Oh ok! I'll try :)

**Comment by Sheshank-s** [comment]
@coke11 I commited some code. Waiting for the website to update. Not sure if it will work though :(

**Comment by coke11** [comment]
@GreenBayRules Didn't work :(

**Comment by zspri** [comment]
@coke11 Once you get it to work,  I can use dev@dragondrops.net and connect the OAuth via that.

**Comment by coke11** [comment]
OK. I am working on getting it setup :).

**Comment by coke11** [comment]
@NaturalmotionStudios But wait - wouldn't that have to be a google account?

**Comment by coke11** [comment]
@GreenBayRules I am going to unassign you because this is hooked up to @NaturalmotionStudios's email

**Comment by zspri** [comment]
@coke11 You can use different domains with Gmail I think.
maybe https://support.google.com/a/answer/6398669?hl=en?
Anyways, I would try it. We could use it for development feedback.

**Comment by zspri** [comment]
I need the other devs to hook this up to the DragonDrop account, or else it won't even work.

**Comment by radioblahaj** [comment]
Even i noticed the issue with the google sign in ! I think we should have some Javasprict app or make our own sign with google app or we can set it up from dragondrops google account

**Comment by zspri** [comment]
@zebraislearning 

> Even i noticed the issue with the google sign in !

That's because of Github. 

> think we should have some Javasprict app or make our own sign with google app or we can set it up from dragondrops google account

We're making a Chrome extension, and Google sign-in we'll have to hook up to the account system thing.

**Comment by radioblahaj** [comment]
Yeah that is what I was thinking

**Comment by radioblahaj** [comment]
I said that on issue #77

**Comment by zspri** [comment]
Ok :)

**Comment by zspri** [comment]
I'll look into it 👌

**Comment by coke11** [comment]
@Nanomotion This is not an issue at the moment and does not need attention as we don't really have a system that we are following for the login and this is just another thing that we will end up changing later.

**Comment by zspri** [comment]
@coke11 Okay, but at some point we need to set up the login before release.

**Comment by coke11** [comment]
Yes, that is why I put it in the backlog. I am going to change the label here just a second.

**Comment by coke11** [comment]
Closing because of #97
