### ISSUE TITLE
dragondro.ps?

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#63]
Can someone reserve a domain with the name `dragondro.ps` before someone else takes it? Thanks

**Comment by coke11** [comment]
.ps?

**Comment by zspri** [comment]
https://en.wikipedia.org/wiki/.ps

**Comment by coke11** [comment]
oh

**Comment by Sheshank-s** [comment]
Cool! But Im not sure any of us are from Palestine, and it could end up being a waste in money D:

**Comment by zspri** [comment]
No, it's just one of those domain things, like `youtu.be`. `dragondro.ps` as in DragonDrops

**Comment by coke11** [comment]
Could we register like dragondr.op?

**Comment by zspri** [comment]
@coke11 It's not a domain :(

(Since it seemed like you were confused: I think it's "better" to have dragondro.ps than dragondrops.net, and it won't matter if it's located in Palestine)

**Comment by coke11** [comment]
OH.

**Comment by Sheshank-s** [comment]
I dont think we should have this as a "issue" Maybe put it as a card on trello

**Comment by coke11** [comment]
@GreenBayRules I have decided that I am not going to get the domain anyhow.
