### ISSUE TITLE
Errors on various pages

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#68]
index.html: (Fixed)

signup.html: (Fixed)

Non-ScratcherContact.html: (Fixed)

videos.html: (An error that we can't fix)
![capture](https://cloud.githubusercontent.com/assets/19719195/18809094/08873b9c-8242-11e6-8fcf-69949b50166e.PNG)

about.html: (An error that we can't fix)
![capture](https://cloud.githubusercontent.com/assets/19719195/18809109/6c1f6f94-8242-11e6-8e25-fc26f2017bb2.PNG)

**Comment by coke11** [comment]
You hacked into mine and Card's chat? Jk - it just happens that this is what I was working on with him. I think some of these are just because we are running it on GithubPages. But others are our fault. I am going to try running these locally or on our server :)

**Comment by coke11** [comment]
@csf30816 Any chance you could run a couple of these locally?

**Comment by zspri** [comment]
@coke11 It's just the Chrome console, lol.
But we need to fix the insecure HTTP requests, the browsers block them, which may lead to other errors.

**Comment by coke11** [comment]
@NaturalmotionStudios I know, but

**Comment by zspri** [comment]
@coke11 ?

**Comment by coke11** [comment]
@NaturalmotionStudios Github might have some errors in Github pages, that are not in our code, but rather their code. Therefore, I am going to run this locally, or on our servers and see if we get the same errors.

**Comment by zspri** [comment]
@coke11 Ah, ok

**Comment by csf30816** [comment]
@coke11 Sorry, can't host it locally now... The 404's are because those files do not exist yet... The https issue is because https is secure so it does not load content that is not https unless you allow it... Glad I could help :)

**Comment by zspri** [comment]
@csf30816 It's not ALL HTTPS errors, the `ReferenceError`s need to be fixed.

**Comment by csf30816** [comment]
OK,

**Comment by zspri** [comment]
Fixed all of the issues that we have control over, the other ones are in Youtube's coding.
