### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/dragon-drop-scratch.github.io#70]
We need to work on making all of our pages mobile friendly.

**Comment by zspri** [comment]
I can try, but I'm not sure how to do that.

**Comment by coke11** [comment]
@NaturalmotionStudios I am going to move this to Trello. https://trello.com/c/JVWwtw1N/192-mobile

**Comment by coke11** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile](https://trello.com/c/JVWwtw1N/192-mobile)

**Comment by csf30816** [comment]
OK

**Comment by coke11** [comment]
@adri326 Would you like to take this?

**Comment by coke11** [comment]
(we just need this on www)

**Comment by adri326** [comment]
I can take this, yeah, I know how to do that

**Comment by zspri** [comment]
We could use a responsive navigation bar so it would be more mobile friendly, just like w3school's at http://www.w3schools.com/howto/howto_js_topnav.asp.

**Comment by zspri** [comment]
Also, just an FYI: the Google Mobile Friendly Test says that our site isn't mobile friendly.
![capture](https://cloud.githubusercontent.com/assets/19719195/21161161/7e4befce-c155-11e6-8242-d1d100e72d2c.PNG)

**Comment by coke11** [comment]
Hey guys. This is what the problem is of the mobile friendliness of our site. We are redirecting all mobile users to a mobile page that is down, when we simply could just  be making some improvements to the code on the desktop site, and then it would look great on mobile. I am going to put this in the before release milestone, because the fix is not necessary atm.

BTW - @golden-scratch and I are working on a Trello notice that really, really should get DD back up!

**Comment by zspri** [comment]
Yes, we really should get started again on it. I'm relieved that I'm not the only one who still cares about DD!

But, back to the issue:
We _could_ use a redirect, but it probably isn't the best solution. Maybe http://www.practicalecommerce.com/articles/115764-make-your-website-mobile-friendly-now-3-ways could help us?

**Comment by card100** [comment]
Hola

**Comment by coke11** [comment]
@card100 Hey, how are you?

**Comment by card100** [comment]
Good

**Comment by card100** [comment]
Will we have the editor on Mobile?

**Comment by zspri** [comment]
@card100 Probably not, we'll just have an app for mobile.

**Comment by card100** [comment]
ok
