### ISSUE TITLE
Color Scheme Change

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/dragon-drop-scratch.github.io#71]
We need to get the color scheme updated to the red theme (same as the logo). The HEX values are #A52D35. We need to work on getting the new scheme JUST on WWW. Then we will focus on having it on the other repros.

I am not going to assign this to anyone. Could @adri326 or @zebraislearning possibly do it, though? (and you guys could submit it in a PR if you don't have write access). Thanks so much!

**Comment by csf30816** [comment]
OK

**Comment by csf30816** [comment]
Done

**Comment by radioblahaj** [comment]
so what do you want me to do ?

**Comment by coke11** [comment]
@zebraislearning Never mind - @csf30816 finished it :)

**Comment by radioblahaj** [comment]
But i wanted to jelp dragondrop! Is there anuthing else i can help you with
@coke11 ?
