### ISSUE TITLE
Prototype's background button does not transfer to preveiw

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#73]

**Comment by coke11** [comment]
@card100 @NaturalmotionStudios ?

**Comment by zspri** [comment]
@coke11 Actually, idk

**Comment by card100** [comment]
The background button that can change the background does not change the css in the preview or export html

**Comment by zspri** [comment]
@card100 Oh, that's a pretty important feature for the editor. @dragon-drop-scratch/coding

**Comment by coke11** [comment]
Oh. This should be in the editor repro then...
