### ISSUE TITLE
dragondrops.net is not going to blog (or anything else)

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#74]

**Comment by zspri** [comment]
Ask @coke11

**Comment by coke11** [comment]
@card100 @NaturalmotionStudios Something is going on with the server. I am working on fixing it. (for now on use Trello for this kind of stuff - thanks)

**Comment by zspri** [comment]
@coke11 All I did was tell @card100 to ask you. :/
