### ISSUE TITLE
Messages icon on dashboard gone

### ISSUE THREAD

**Issue by card100** [dragon-drop-scratch/dragon-drop-scratch.github.io#82]
csf30816, you seemed to make the messages button disappear.  Please don't be kidnapping icons.  Thank You for your understanding.

**Comment by zspri** [comment]
@card100 @csf30816 Kidnapping icons?

**Comment by Sheshank-s** [comment]
Lol

Sent from my iPhone

On Sep 28, 2016, at 3:43 AM, Nanomotion <notifications@github.com<mailto:notifications@github.com>> wrote:

@card100https://github.com/card100 @csf30816https://github.com/csf30816 Kidnapping icons?

**Comment by csf30816** [comment]
?

**Comment by coke11** [comment]
Please make sure you are putting issues in the right repros. Thanks
