### ISSUE TITLE
iframe broken on /admin/ page

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#83]
Iframe doesn't go all the way down the page. 
![capture](https://cloud.githubusercontent.com/assets/19719195/19214269/a8f912ca-8d4c-11e6-9242-c581671bb003.PNG)

**Comment by coke11** [comment]
@NaturalmotionStudios How is it broken? Please be more specific when filling issues. Thanks :)

**Comment by zspri** [comment]
@coke11 Updated description

**Comment by Sheshank-s** [comment]
I will try to fix this :)

**Comment by Sheshank-s** [comment]
Done :)

**Comment by zspri** [comment]
@GreenBayRules Thanks!
