### ISSUE TITLE
Github Website

### ISSUE THREAD

**Issue by radioblahaj** [dragon-drop-scratch/dragon-drop-scratch.github.io#85]
To me The github site is looking very bad, Can we fix it ! @GreenBayRules I think you did a big mistake!

**Comment by GreenBayRules** [comment]
Thanks. That was very nice. I didn't make a mistake. I was trying something out. I was changing up the credits page ok? How about you go check out the page now? I fixed it. So next time, before you start go accusing people for mistakes, why don't you think about submitting a pull request to fix it? Thanks!

**Comment by zspri** [comment]
@zebraislearning Please be considerate of the DragonDrop team members.

**Comment by radioblahaj** [comment]
Ok

**Comment by radioblahaj** [comment]
HEY!

**Comment by zspri** [comment]
Please stop
