### ISSUE TITLE
Credits Page Retired People

### ISSUE THREAD

**Issue by Sheshank-s** [dragon-drop-scratch/dragon-drop-scratch.github.io#86]
I was gonna do this. But it might take a while. If anyone wants to do it, that is great, just un assign me and put yourself :D

**Comment by zspri** [comment]
I would do it but Github is being a little annoying lately, I could try if you want.

**Comment by Sheshank-s** [comment]
Ok, I guess you will do it because I already have quit Dragon Drop.

**Comment by MeridiumDevelopment** [comment]
...

**Comment by zspri** [comment]
@GreenBayRules Wait, wait, wait! What?

**Comment by coke11** [comment]
@GreenBayRules Don't worry! He came back :)

**Comment by zspri** [comment]
@coke11 Ah, ok

**Comment by zspri** [comment]
Done with the code, I just need the profile pictures.
