### ISSUE TITLE
Typed div not working

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#87]
It does this for a few seconds then returns to normal:
![capture](https://cloud.githubusercontent.com/assets/19719195/19418027/818c6820-9389-11e6-8a7b-81d93fd8e71c.PNG)

**Comment by card100** [comment]
Not sure how we should fix it

**Comment by Sheshank-s** [comment]
I know.. I didn't create that thing on the index. Ask @csf30816 I _think_ he made it. It  could be @coke11 
I guess they should be the one assigned.

**Comment by zspri** [comment]
@GreenBayRules @card100 We could just get rid of it, or make it a GIF.

**Comment by coke11** [comment]
I can not repro this even If I try a thousand times. In order to prevent these kinds of things from happening again, even if we get them fixed is leaving better notes when you make a change.
