### ISSUE TITLE
Browser Issue?

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#89]
I got bored at school and decided to go on DragonDrop using Firefox... The site looked a little bit weird
![capture](https://cloud.githubusercontent.com/assets/19719195/19494135/a7d65720-954b-11e6-9d4e-fdef8c0c6aad.PNG)
![capture2](https://cloud.githubusercontent.com/assets/19719195/19494144/ab5fa6e4-954b-11e6-81fa-f1238433011c.PNG)
Maybe we could add a banner that says <i>Things looking different? That may because of your browser. DragonDrop works best with <b>Google Chrome</b></i> at the top of the page.

**Comment by Sheshank-s** [comment]
Hm ok.. I never use Firefox at school.. I installed chrome.. But don't tell my teacher 😃

Sent from my iPhone

On Oct 18, 2016, at 1:00 PM, Nanomotion <notifications@github.com<mailto:notifications@github.com>> wrote:

I got bored at school and decided to go on DragonDrop using Firefox... The site looked a little bit weird
[capture]https://cloud.githubusercontent.com/assets/19719195/19494135/a7d65720-954b-11e6-9d4e-fdef8c0c6aad.PNG
[capture2]https://cloud.githubusercontent.com/assets/19719195/19494144/ab5fa6e4-954b-11e6-81fa-f1238433011c.PNG
Maybe we could add a banner that says Things looking different? That may because of your browser. DragonDrop works best with Google Chrome at the top of the page.

**Comment by zspri** [comment]
@GreenBayRules Lol, but how would we do the banner or should we even do it at all?

**Comment by Sheshank-s** [comment]
Not sure

Sent from my iPhone

On Oct 19, 2016, at 4:19 AM, Nanomotion <notifications@github.com<mailto:notifications@github.com>> wrote:

@GreenBayRuleshttps://github.com/GreenBayRules Lol, but how would we do the banner or should we even do it at all?

##

**Comment by zspri** [comment]
I think we should :P

**Comment by adri326** [comment]
I always use firefox developer edition and it works nice. Could you grab the version of firefox that your school is "running"?

**Comment by zspri** [comment]
@adri326 49.0.2.11on Windows 8.1 Pro 

And I installed Firefox on my regular PC, so it may just be that either it's an outdated version of Firefox, or it's just because Windows 8.1 is an outdated OS.

**Comment by card100** [comment]
Does this help?:
http://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser

**Comment by Sheshank-s** [comment]
It should... ask nanomotion

Sent from my iPhone

On Oct 20, 2016, at 7:26 AM, card100 <notifications@github.com<mailto:notifications@github.com>> wrote:

Does this help?:
http://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser

##

**Comment by zspri** [comment]
@card100 Yes, thanks. @GreenBayRules I get the `var` part, but how would we add the banner?

``````
    function detectBrower() { 
     if(navigator.userAgent.indexOf("Firefox") != -1 ) {
         showBrowserBanner();
     } else {
         showBrowserBanner();
     } }```
``````

**Comment by adri326** [comment]
Have the banner as a simple element:
`<div id="browserBanner" style="visibility: hidden">Blah blah blah</div>`, then when the page has loaded (eventListener), just change the visibility to visible:

``````
function showBrowserBanner() {
  document.getElementById("browserBanner").style.visibility = "visible";
}```
``````

**Comment by zspri** [comment]
@adri326 Yes, would you mind doing it? If you could, that'd be great.

**Comment by adri326** [comment]
Only on the index.html or server-wide?

**Comment by adri326** [comment]
Done! Need checking because I'm doing that from Bali on my dad's IPhone. The box doesn't have any style - typing on an iPhone is _painful_. Why did apple put every useful characters in the advanced special chars keyboard?

**Comment by zspri** [comment]
Thanks!

**Comment by Sheshank-s** [comment]
You would have a div and u would set the inner html to visible true or something like that

Sent from my iPhone

On Oct 20, 2016, at 3:00 PM, Nanomotion <notifications@github.com<mailto:notifications@github.com>> wrote:

@card100https://github.com/card100 Yes, thanks. @GreenBayRuleshttps://github.com/GreenBayRules I get the var part, but how would we add the banner?

``````
function detectBrower() {
 if(navigator.userAgent.indexOf("Firefox") != -1 ) {
     showBrowserBanner();
} else {
   showBrowserBanner();
} }```
``````

##

**Comment by Sheshank-s** [comment]
What i meant

Sent from my iPhone

On Oct 21, 2016, at 6:36 PM, adri326 <notifications@github.com<mailto:notifications@github.com>> wrote:

Have the banner as a simple element:
<div id="browserBanner" style="visibility: hidden">Blah blah blah</div>, then when the page has loaded (eventListener), just change the visibility to shown:

function showBrowserBanner() {
  document.getElementById("browserBanner").style.visibility = "shown";
}```

##

**Comment by coke11** [comment]
Firefox is a big browser. Rather then telling people to switch why don't we just optimize our site for firefox?

**Comment by zspri** [comment]
It's not just Firefox. There are other browsers that render the site differently. e.g., Edge:
![capture](https://cloud.githubusercontent.com/assets/19719195/22526999/840cdaa0-e89b-11e6-98bb-f12b6058eb7c.PNG)

But we should fix the CSS first, before we worry about this.

**Comment by coke11** [comment]
@Nanomotion Yeah, edge is pretty big too. We will need to fix it for all major browsers. We need to do a better job of getting the QA's checking every little things lol. (can you get on slack BTW)

**Comment by zspri** [comment]
Yes, we will need to. Sure thing :P

**Comment by Sheshank-s** [comment]
![image](https://cloud.githubusercontent.com/assets/11379161/22766838/9db50a86-ee2c-11e6-87b3-2ee94912db71.png)

**Comment by zspri** [comment]
This is turning into "spot the differences"

Firefox:
![capture](https://cloud.githubusercontent.com/assets/19719195/22806119/8b244266-eeee-11e6-8c99-842f73b6d9fa.PNG)

Chrome:
![capture2](https://cloud.githubusercontent.com/assets/19719195/22806126/9667d520-eeee-11e6-9353-05b22f9d619a.PNG)

Edge:
![capture3](https://cloud.githubusercontent.com/assets/19719195/22806135/9c77240c-eeee-11e6-9d04-6068c12b681b.PNG)

**Comment by zspri** [comment]
Closing this as irrelevant now.
