### ISSUE TITLE
FAQ errors

### ISSUE THREAD

**Issue by Sheshank-s** [dragon-drop-scratch/dragon-drop-scratch.github.io#92]
![image](https://cloud.githubusercontent.com/assets/11379161/20285986/908aa538-aa79-11e6-8d93-2fac81434300.png)
There were a couple of glitches after cards update, they seem very minor it could just be typos. 

I would do this, but as some of you know I cant work till December, so maybe someone else wants to fix it?

**Comment by radioblahaj** [comment]
![errorfaqdragondrop](https://cloud.githubusercontent.com/assets/21000033/21082102/285692c2-bfa2-11e6-9287-efc14377b9ca.png)

Even i found the same thing! It looks pretty akward!

@coke11

**Comment by MeridiumDevelopment** [comment]
Scanning over the code, there was an extra </div> which caused all the fancy containers to stop. After removing that, it's all done.

Thanks for bringing this up. Sorry for not checking it sooner

Closed

**Comment by zspri** [comment]
@zebraislearning Coke11 is not the only one who is working on this project, feel free to tag any staff at any time.

**Comment by Sheshank-s** [comment]
@nanomotion lol

Sent from my iPhone

On Dec 13, 2016, at 1:53 PM, Nanomotion <notifications@github.com<mailto:notifications@github.com>> wrote:


@zebraislearning<https://github.com/zebraislearning> Coke11 is not the only one who is working on this project, feel free to tag any staff at any time.

**Comment by radioblahaj** [comment]
Sure I just did that for fun! @packersNfl

**Comment by zspri** [comment]
@GreenBayRules ¯\\\_(ツ)_/¯

@zebraislearning "For fun"? lol
