### ISSUE TITLE
Login Change

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/dragon-drop-scratch.github.io#97]
I know this is a little late, but I would like for our login to go. It's been a long ride, log in!

Here, allow me to explain.

The login we have right now is an awesome login. However, as we need more and more features we are using Auth0 anyway, and I think that we should just use Auth0 for everything. Another problem is that we have all of these test databases floating around, and we don't have anything for the login organized. We are just spending to much time on something that, frankly shouldn't even be that hard.  It is also just really hard to test this out right now, and of course, there's is probably a lot more secure.

I am guessing the question you are asking yourself right now is 

> What about the Scratch login?

Right? Well, as you may have noticed DragonDrop has not been doing as much on Scratch lately. Now, we are going to use Scratch as a form of communication. After all, Scratch users are really just normal people, and they don't really need different features and accounts. So with that, the Scratch account feature is no longer necessary.

Thank you for all of your hard work. I will get an Auth account created and get it out there on slack.

**Comment by zspri** [comment]
We could use the Google Login API. It's free and fairly easy to use.

**Comment by coke11** [comment]
@Nanomotion We could use that AND Auth0... Auth0 is free for one login source.

**Comment by zspri** [comment]
True, to add more flexibility.

**Comment by coke11** [comment]
The official course of action will be what has been discussed in the threads above this post.

**Comment by radioblahaj** [comment]
Cool

**Comment by Sheshank-s** [comment]
Why do you comment on this like 7 months after xD
