### ISSUE TITLE
Rethinking the Editor

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#98]
It has become apparent to me that the DragonDrop editor needs a huge redesign. Not in the design aspect, but rather coding aspect. When someone creates a website, I really would like the slogan "Create Your Website Easly in minutes" to be true. Although we have a great prototype going, we really need to make a way so the features we put in place are not as limited. If you don't know what I mean, don't worry. I will explain.

if you visit a site such as Wix or Weebly you can see that elements can be moved wherever you want to move them to, with limits. However with the prototype when you drop an element it just goes slightly below where you dropped it. I am looking to change this. I think when you drop and element it should go right where you dropped it. Then you can move your element, as well as changing the size. There would be more tools also. Allow me to give a few cases where this would be useful:

1) Jim is creating a site with a header. There is no header tool in DragonDrop. He can upload an image, stretch it to the size he wants his header to be, and move it up to the top. Then he can grab a text tool, and place it where he wants it to go on the header. He can change the text, and then the size of the element. Now he has a header!

2) We would have to create a lot fewer tools.

-- EDIT from @Nanomotion: Header tools are still useful, and we should keep them.

Let me know what you think of this. Then we can work on getting it added :)

Below is a progress list:

- [x] When you drag a picture, there will be no pop-up.  The picture will just go exactly where you dragged it. The default picture will just be a stock image. Then you can click on the picture to change it, and move it around. You can also drag corners to change the size.

- [x] Forget the text pop-up. Now text will just go where you dropped it. With something along the lines of "enter your text here" for the automatic text (you could change it) You can highlight the text/right click to change styling, use tools like you would see in word, add links, etc.

- [x] Get rid of the link option. Because of what I said above it is no longer necessary.

- [ ] Keep the Scratch pop-up. However make it so you can edit the project idea by clicking on the embed after it is in, clicking on a settings gear and changing the ID. Also, make it so it goes just where your mouse is when you drag it. And you can change the size by the corners.

- [x] Make the font the same in the preview as it is in the editor

- [ ] Need to add a youtube viceo? No probelm! Instead of asking user to enter the ID, allow them to search the site. Once they find the video they need they can click ok, and it will imprt. 

- [ ] Make it so you can simply change the size of all elemts using arrow tools. 

- [ ] Add a button tool, which can go to a page, section ID, or link

- [ ] Add the option to create a section id. The user would have to hover over the text they wanted the ID to be on, right click, and click new section ID. They would enter their ID.

- [x] Work on Right Click 

(NOTE: This issue was transferred over from Trello, @coke11 made the original)

**Comment by coke11** [comment]
@Nanomotion Do you think you could add the list?

**Comment by zspri** [comment]
I don't think there was a list with the Trello card.

**Comment by coke11** [comment]
@Nanomotion There was, but you don't need to worry about it. I have it under control.

**Comment by zspri** [comment]
@coke11 Ok, thanks.

**Comment by csf30816** [comment]
Hello in a new repository I will make a new Editor, the design will be different in both design and code aspects. I have spent the past 4 months practicing my design and programming skills. I will keep you informed on the new editor.

Thanks, - Csf30816.

**Comment by coke11** [comment]
@csf30816 I can tell from looking at http://drive.awatim.gq :D. Do you think it would be possible to just do it in the editor folder here?

**Comment by csf30816** [comment]
Yes, but first I must test it.

**Comment by coke11** [comment]
@csf30816 Awesome! Have you seen my Scratch comment?

**Comment by csf30816** [comment]
Yes

**Comment by coke11** [comment]
@csf30816 Could you get on slack?

**Comment by csf30816** [comment]
Sure

**Comment by csf30816** [comment]
Note: all my fixes are made here `https://dragon-drop-scratch.github.io/editor_test/editor/`
