### ISSUE TITLE
Additional Projects

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#99]
These are projects we will need to do later:

- [ ] Analytics
- [ ] Tutorials
- [ ] "Made With DragonDrop" site
- [ ] DragonScript
- [ ] DragonEd (Education for DragonDrop)

**Comment by card100** [comment]
All Added to https://github.com/dragon-drop-scratch/dragon-drop-scratch.github.io/issues/115
